### ISSUE TITLE
capacity filter not works in CapRover dashboard unlike the one in the play

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtecharchive/caprover-frontend#4]
capacity filter in CapRover dashboard not able to find nodes to add to the cluster unlike the capacity filter in the play.

happens on: TestNet
didn't test with DevNet as currently, it suffers from IPv4 address exhaustion.

![Peek 2021-12-20 20-42](https://user-images.githubusercontent.com/42457449/146816952-ece1a27c-dc2a-4b93-be58-19ce313764fe.gif)

**Comment by abom** [comment]
Should be resolved by https://github.com/freeflowuniverse/caprover-frontend/commit/98596db4384a8ac2f6e4938d8964fe24636cb840 and new docker image is pushed.

**Comment by sameh-farouk** [comment]
verifying this

**Comment by sameh-farouk** [comment]
now it can find nodes but is not able to deploy, should this be tracked here or do you prefer to be on a new issue?

```
Error
An error occurred while trying to deploy a worker node:
Error: Validation failed. errors: An instance of e has failed the validation: - property name has failed the following constraints: maxLength, isAlphanumeric ,An instance of e has failed the validation: - property network.name has failed the following constraints: maxLength, isAlphanumeric ,An instance of e has failed the validation: - property machines[0].name has failed the following constraints: maxLength, isAlphanumeric
```

![Peek 2021-12-21 16-52](https://user-images.githubusercontent.com/42457449/146950236-0301c285-fa0f-4da5-a694-a831176498ff.gif)

**Comment by abom** [comment]
Updated names generation to pass these constraints at https://github.com/freeflowuniverse/caprover-frontend/commit/93319198dafc88c8ea0349c8e3977b18ab3af6ac, new image is pushed too.

**Comment by sameh-farouk** [comment]
Verified. works now as expected.
![Screenshot from 2021-12-22 01-32-11](https://user-images.githubusercontent.com/42457449/147064015-5752214e-fb4b-44ee-aef0-ac21b6485c08.png)
