### ISSUE TITLE
We should not allow users to add new nodes without setting up a repository first.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtecharchive/caprover-frontend#5]
the Captain [docs](https://caprover.com/docs/app-scaling-and-cluster.html) states

> For cluster mode (more than one server) you will need to have a default push Docker Registry.

and

> Note that before switching to cluster from a single node, if you have any existing app, you will have to set up Registry and re-deploy all your existing apps to make sure they are pushed to the registry and are available to all nodes, not just the main leader node.

If you try to add a new node through the captain dashboard native way (Attach New Node section in cluster tab) without setting up a registry first it will through this error message:
`1000 : There is no default Docker Registry. You need a repository for your images before adding nodes. Read docs.`

however, now we give the user an alternative way to add a node on the grid, switching to cluster mode without having a registry (bypassing the check) **which causes apps to be deployed only on the leader node** (when you build and deploy from source code).

so we should **flow captain rules and validate that the user has set up a docker registry before allowing him to proceed further and add a node**.

### steps to reproduce:
- add a new node from the cluster -> Deploy a new node on Threefold grid
- Inside CapRover repo, you can find a collection of different sample apps that are ready to be deployed! See: https://github.com/caprover/caprover/tree/master/captain-sample-apps
- Download the tar file of your choice.
- Go to your CapRover web dashboard -> Apps tab and create a test app.
- Go to the "Deployment" tab and upload the tar file.
- scale the app configs to 5 or 6 instances
- check where the instances running, from the terminal by running command `docker node ls` then `docker node ps {node-id}`
- check both nodes, you will find all instances running on the leader node, while in the worker node/s it was rejected with error `"Err": "No such image: img-captain-my-test-app:4"`

**Comment by abom** [comment]
Should be fixed at a3d8673f24d5dde436c94ca9c6e81b0cc005469d
